version: '3.9'

services:
    postgres:
        image: postgres:15.5-alpine
        # expose:
        #     - "5432"
        ports:
            - "5432:5432"
        restart: always
        volumes:
            - wallet_tracker_volume:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            TZ: Europe/Lisbon
            PGTZ: Europe/Lisbon

    phoenix:
        build:
            dockerfile: dockerfile
        image: phoenix
        ports:
            - "4000:4000"
        volumes:
            - ./app:/home/app
        command: >
            bash -c "mix setup && elixir --sname cookie --cookie monster -S mix phx.server"
        environment:
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_DATABASE: ${POSTGRES_DATABASE}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            HOST: ${HOST}
            SECRET_KEY_BASE: ${SECRET_KEY_BASE}
            ERL_AFLAGS: -kernel shell_history enabled
        restart: always
        depends_on:
            - postgres

volumes:
    wallet_tracker_volume: