#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".
set -e

docker-compose run -T --rm phoenix sh pre-commit-script > git-commit.error.log 2>&1 || (echo "Error: pre-commit checks failed. Check git-commit.error.log for more details." && 2>&1 && exit 1)
rm git-commit.error.log